#!/usr/bin/env python3
"""cortextOS org backup — Step 1 (zip + email) + Step 2 (FTPS off-site).

Zips the silvermere-tech org's durable knowledge and config, then:
  - DAILY: emails the zip to bertha@silvermere.tech (self-managed retention,
    last 7 daily backups kept via IMAP prune).
  - WEEKLY (Sundays, or pass --weekly): also emails the zip to
    steven.barker@silvermereconsulting.com as an offsite copy.
  - STEP 2 (if BACKUP_FTP_HOST configured in secrets.env): uploads the zip
    to an FTPS target for true off-site backup. Runs regardless of zip size
    — provides off-site backup for ALL daily zips, not just the oversized
    ones that fail the email path. Includes retention pruning.

Both email sends use the system path (no auto-CC). The weekly send is TO
Steven by design, not a CC — it's his explicit offsite copy.

SIZE GUARD on email: zips exceeding SIZE_LIMIT_MB are sent as a no-attachment
notification only — the FTP step (Step 2) is the recovery path for those.
If FTP is not configured AND the zip is oversized, the email body says so
explicitly so a human can manually intervene.

Usage:
  backup.py                   # daily mode (auto-weekly on Sundays)
  backup.py --weekly          # force weekly send today
  backup.py --dry-run         # build + size-check the zip, don't send
  backup.py --no-ftp          # skip Step 2 even if configured (one-off testing)

CONFIG (secrets.env keys for Step 2 — all optional; absence = Step 2 disabled):
  BACKUP_FTP_HOST              FTPS hostname (REQUIRED to enable Step 2)
  BACKUP_FTP_PORT              FTPS port (default 21)
  BACKUP_FTP_USER              login
  BACKUP_FTP_PASSWORD          login password
  BACKUP_FTP_PATH              remote dir for backups (default /)
  BACKUP_FTP_RETENTION_DAYS    purge older zips after N days (default 30)

TODO Step 3: restore script in restore.py (companion to this script).
"""
import argparse
import ftplib
import imaplib
import os
import re
import shutil
import smtplib
import ssl
import subprocess
import sys
import tempfile
import zipfile
from datetime import datetime, timezone
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

ORG_ROOT = Path("/home/cortext/cortextos/orgs/silvermere-tech")
SECRETS_FILE = Path("/home/cortext/cortextos/orgs/silvermere-tech/secrets.env")
SIZE_LIMIT_MB = 20
DAILY_DEST = "bertha@silvermere.tech"
WEEKLY_DEST = "steven.barker@silvermereconsulting.com"
KEEP_DAILY = 7
# Durable on-box retained copy. The zip is otherwise built in a TemporaryDirectory
# and discarded on exit — so on oversized days (no email attachment) with FTPS
# unconfigured there was NO retained copy anywhere. This guarantees at least one.
LOCAL_RETAIN_DIR = Path("/home/cortext/backups/org-daily")
KEEP_LOCAL = 14
BACKUP_SUBJECT_PREFIX = "[BACKUP]"

# Step 2b — off-host copy to the OVH gateway (internal infra, our own box).
# True off-host copy that survives total loss of the app VM. The gateway is a
# small 2.0G LXC, so retention is kept lean (zip ~55MB → 7 copies ~385MB).
GATEWAY_REMOTE_DIR = "/home/cortext/backups/silvermere-org"
KEEP_GATEWAY = 7

# Paths to include in the zip (relative to ORG_ROOT).
# Explicit inclusion list keeps the zip predictable and avoids accidental
# credential leaks (secrets.env, gsc-service-account.json are excluded).
INCLUDE_PATTERNS = [
    "knowledge.md",
    "context.json",
    "goals.json",
    "brand_tone.md",
    "brand-voice.md",
    "docs",
    "research",
    "scripts",
    # Per-agent bootstrap + memory (config.json, *.md, memory/*.md)
    "agents/*/config.json",
    "agents/*/*.md",
    "agents/*/memory",
    # Project docs (exclude clearspeak-studio/app — node_modules/build, ~641MB)
    "projects/gamesonthemove",
    "projects/business-in-a-box",
    "projects/dog-supplements",
    "projects/hiba-ventures",
    "projects/dashboard-tooling",
    "projects/server-reselling",
    "projects/smb-discovery",
    "projects/silvermere-tech-email",
    "projects/foundry",
    "projects/clearspeak-studio",  # node_modules/build/dist/.next stripped by EXCLUDE_DIRS
]

# Always exclude these patterns even if matched above
EXCLUDE_SUFFIXES = {".env", ".key", ".pem", ".p12", ".pfx", ".tsbuildinfo"}
EXCLUDE_NAMES = {"secrets.env", "gsc-service-account.json", ".env"}
EXCLUDE_DIRS = {"node_modules", ".git", "__pycache__", ".next", "dist", "build", ".cache"}


def load_secrets():
    secrets = {}
    with open(SECRETS_FILE) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            secrets[key.strip()] = val.strip()
    return secrets


# Clean-backup principle (Steve, 2026-06-24): back up source-of-truth, drop
# DERIVED artifacts. A PDF generated by doc-to-pdf.js is derived — it rebuilds
# from its source .md on restore — so it is excluded IFF a verified source .md
# exists. doc-to-pdf.js prepends a project-code prefix to the generated PDF
# filename (orgs/silvermere-tech/docs/wow-project-codes.md); we strip a known
# code prefix from the PDF stem before matching it to a same-directory .md.
# Match is same-dir + exact stem (version+date included) → high precision.
# When NO matching .md exists (orphan / external/provided PDF) → KEPT.
PROJECT_CODES = ["BiB", "ClSp", "Stry", "KMIP", "Hba", "Plnt", "GOTM", "Wllsp",
                 "SvrRs", "MCSv", "Bud", "HmOr", "FCal", "Fndy", "PCMsg", "SchE",
                 "cvSBH", "SrEm", "SCFr", "LFA", "TriOM", "FamD"]
_CODES_LC = sorted({c.lower() for c in PROJECT_CODES}, key=len, reverse=True)
_md_stem_cache: dict = {}


def _strip_code(stem: str) -> str:
    s = stem.lower()
    for c in _CODES_LC:
        if s.startswith(c + "-"):
            return s[len(c) + 1:]
    return s


def _dir_md_stems(directory: Path) -> set:
    """Cached set of code-stripped .md stems in a directory."""
    key = str(directory)
    if key not in _md_stem_cache:
        stems = set()
        try:
            for m in directory.glob("*.md"):
                stems.add(_strip_code(m.stem))
        except OSError:
            pass
        _md_stem_cache[key] = stems
    return _md_stem_cache[key]


def is_regenerable_pdf(path: Path) -> bool:
    """True if path is a PDF with a verified same-directory .md source sibling
    (derived artifact → excluded). False for non-PDFs and orphan/external PDFs
    with no .md source (→ kept). See clean-backup principle above."""
    if path.suffix.lower() != ".pdf":
        return False
    return _strip_code(path.stem) in _dir_md_stems(path.parent)


def should_exclude(path: Path) -> bool:
    if path.name in EXCLUDE_NAMES:
        return True
    if path.suffix.lower() in EXCLUDE_SUFFIXES:
        return True
    for part in path.parts:
        if part in EXCLUDE_DIRS:
            return True
    if is_regenerable_pdf(path):
        return True
    return False


def add_to_zip(zf: zipfile.ZipFile, src: Path, arc_base: Path) -> list[str]:
    """Recursively add src to zf, returning list of skipped paths."""
    skipped = []
    if src.is_file():
        if should_exclude(src):
            skipped.append(str(src))
        else:
            zf.write(src, arcname=src.relative_to(arc_base))
    elif src.is_dir():
        for child in sorted(src.rglob("*")):
            if child.is_file() and not should_exclude(child):
                zf.write(child, arcname=child.relative_to(arc_base))
            elif child.is_file():
                skipped.append(str(child))
    return skipped


def build_zip(dest_path: str) -> tuple[float, list[str]]:
    """Build the backup zip. Returns (size_mb, skipped_list)."""
    skipped: list[str] = []
    arc_base = ORG_ROOT.parent  # zip paths start from cortextos/orgs/

    seen: set[Path] = set()

    def add_once(zf, src, arc_base):
        """Add src to zip, skipping duplicates."""
        real = src.resolve()
        if real in seen:
            return []
        seen.add(real)
        return add_to_zip(zf, src, arc_base)

    with zipfile.ZipFile(dest_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for pattern in INCLUDE_PATTERNS:
            if "*" in pattern:
                # Use pathlib glob for patterns containing wildcards
                for match in sorted(ORG_ROOT.glob(pattern)):
                    if match.exists():
                        skipped.extend(add_once(zf, match, arc_base))
            else:
                target = ORG_ROOT / pattern
                if target.exists():
                    skipped.extend(add_once(zf, target, arc_base))

    size_mb = os.path.getsize(dest_path) / (1024 * 1024)
    return size_mb, skipped


def retain_local(zip_path: str, date_str: str) -> str:
    """Copy the built zip to a durable local path + prune old copies.
    The on-box retained snapshot — guarantees a retained copy exists even when
    the zip is oversized (no email attachment) AND FTPS is unconfigured."""
    try:
        LOCAL_RETAIN_DIR.mkdir(parents=True, exist_ok=True)
        dest = LOCAL_RETAIN_DIR / f"silvermere-tech-backup-{date_str}.zip"
        shutil.copy2(zip_path, dest)
        zips = sorted(LOCAL_RETAIN_DIR.glob("silvermere-tech-backup-*.zip"))
        pruned = 0
        for old in (zips[:-KEEP_LOCAL] if len(zips) > KEEP_LOCAL else []):
            try:
                old.unlink()
                pruned += 1
            except OSError:
                pass
        size_mb = dest.stat().st_size / (1024 * 1024)
        return f"Local retain: {dest} ({size_mb:.2f} MB); pruned {pruned}, keeping last {KEEP_LOCAL}"
    except Exception as e:
        return f"Local retain: FAILED — {e}"


def send_backup(smtp_host, smtp_port, sender, password, recipient, subject, body, zip_path=None):
    if zip_path:
        msg = MIMEMultipart("mixed")
        msg.attach(MIMEText(body, "plain", "utf-8"))
        with open(zip_path, "rb") as f:
            data = f.read()
        part = MIMEBase("application", "zip")
        part.set_payload(data)
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", "attachment",
                        filename=os.path.basename(zip_path))
        msg.attach(part)
    else:
        msg = MIMEText(body, "plain", "utf-8")

    msg["From"] = sender
    msg["To"] = recipient
    msg["Subject"] = subject

    with smtplib.SMTP_SSL(smtp_host, smtp_port) as smtp:
        smtp.login(sender, password)
        smtp.sendmail(sender, [recipient], msg.as_string())


def _ftp_connect(secrets):
    """Return (FTP_TLS connection, remote_dir) or None if Step 2 not configured."""
    host = secrets.get("BACKUP_FTP_HOST", "").strip()
    if not host:
        return None, None
    port = int(secrets.get("BACKUP_FTP_PORT", 21))
    user = secrets.get("BACKUP_FTP_USER", "").strip()
    password = secrets.get("BACKUP_FTP_PASSWORD", "").strip()
    remote_dir = secrets.get("BACKUP_FTP_PATH", "/").strip() or "/"

    ctx = ssl.create_default_context()
    ftps = ftplib.FTP_TLS(context=ctx)
    ftps.connect(host, port, timeout=60)
    ftps.login(user, password)
    ftps.prot_p()
    # cwd to target dir, creating leaf if necessary
    parts = [p for p in remote_dir.split("/") if p]
    ftps.cwd("/")
    for p in parts:
        try:
            ftps.cwd(p)
        except ftplib.error_perm:
            ftps.mkd(p)
            ftps.cwd(p)
    return ftps, remote_dir


def upload_to_ftp(secrets, zip_path: str) -> str:
    """Upload zip_path via FTPS. Returns one-line status string for email body."""
    try:
        ftps, remote_dir = _ftp_connect(secrets)
    except Exception as e:
        return f"FTP: FAILED to connect — {e}"
    if ftps is None:
        return "FTP: skipped (BACKUP_FTP_HOST not configured)"

    fname = os.path.basename(zip_path)
    try:
        with open(zip_path, "rb") as fh:
            ftps.storbinary(f"STOR {fname}", fh)
        size_mb = os.path.getsize(zip_path) / (1024 * 1024)
        try:
            ftps.quit()
        except Exception:
            ftps.close()
        return f"FTP: uploaded {fname} ({size_mb:.2f} MB) to {secrets['BACKUP_FTP_HOST']}:{remote_dir}"
    except Exception as e:
        try:
            ftps.close()
        except Exception:
            pass
        return f"FTP: upload FAILED — {e}"


_BACKUP_NAME_RE = re.compile(r"^silvermere-tech-backup-(\d{4}-\d{2}-\d{2})\.zip$")


def prune_ftp(secrets) -> str:
    """Delete backup zips on the FTPS target older than retention. Returns status line."""
    retention_days = int(secrets.get("BACKUP_FTP_RETENTION_DAYS", 30))
    try:
        ftps, _ = _ftp_connect(secrets)
    except Exception as e:
        return f"FTP prune: FAILED to connect — {e}"
    if ftps is None:
        return "FTP prune: skipped (not configured)"

    try:
        names = ftps.nlst()
    except Exception as e:
        try:
            ftps.close()
        except Exception:
            pass
        return f"FTP prune: listing FAILED — {e}"

    from datetime import datetime as _dt, timedelta as _td
    cutoff = _dt.now(timezone.utc).date() - _td(days=retention_days)
    deleted = 0
    for n in names:
        m = _BACKUP_NAME_RE.match(os.path.basename(n))
        if not m:
            continue
        try:
            file_date = _dt.strptime(m.group(1), "%Y-%m-%d").date()
        except ValueError:
            continue
        if file_date < cutoff:
            try:
                ftps.delete(n)
                deleted += 1
            except Exception:
                pass

    try:
        ftps.quit()
    except Exception:
        ftps.close()
    return f"FTP prune: deleted {deleted} backup(s) older than {retention_days}d"


def _run_ssh(cmd_args, env, timeout=120):
    """Run an ssh/scp command (cmd_args already starts with 'ssh'/'scp') detached
    from any controlling tty via setsid so SSH_ASKPASS is honoured for password
    auth. Returns (returncode, stdout, stderr)."""
    full = ["setsid", "-w"] + cmd_args
    p = subprocess.run(full, env=env, capture_output=True, text=True, timeout=timeout)
    return p.returncode, p.stdout, p.stderr


def upload_to_gateway(secrets, zip_path: str) -> str:
    """Step 2b — off-host copy of the zip to the OVH gateway over SSH/scp.
    Internal infra (our own box), so no spend/approval gate. Verifies the remote
    byte-size matches local before reporting success, then prunes to KEEP_GATEWAY.
    Returns a one-line status string for the email body."""
    host = secrets.get("TRAEFIK_GATEWAY_HOST", "").strip()
    user = secrets.get("TRAEFIK_GATEWAY_SSH_USER", "").strip()
    password = secrets.get("TRAEFIK_GATEWAY_SSH_PASSWORD", "").strip()
    if not (host and user and password):
        return "Gateway: skipped (TRAEFIK_GATEWAY_* not configured)"

    askpass_path = None
    try:
        fd, askpass_path = tempfile.mkstemp(prefix="bk_askpass_", suffix=".sh")
        with os.fdopen(fd, "w") as f:
            f.write('#!/bin/sh\necho "$GW_SSH_PW"\n')
        os.chmod(askpass_path, 0o700)
        env = os.environ.copy()
        env["GW_SSH_PW"] = password
        env["SSH_ASKPASS"] = askpass_path
        env["SSH_ASKPASS_REQUIRE"] = "force"
        env["DISPLAY"] = env.get("DISPLAY", ":0")

        ssh_opts = ["-o", "StrictHostKeyChecking=accept-new",
                    "-o", "ConnectTimeout=30", "-o", "BatchMode=no"]
        target = f"{user}@{host}"
        fname = os.path.basename(zip_path)
        remote_file = f"{GATEWAY_REMOTE_DIR}/{fname}"

        rc, _out, err = _run_ssh(["ssh"] + ssh_opts + [target, f"mkdir -p {GATEWAY_REMOTE_DIR}"], env)
        if rc != 0:
            return f"Gateway: FAILED (mkdir) — {err.strip() or rc}"

        rc, _out, err = _run_ssh(
            ["scp"] + ssh_opts + [zip_path, f"{target}:{remote_file}"], env, timeout=300)
        if rc != 0:
            return f"Gateway: FAILED (scp) — {err.strip() or rc}"

        # Verify the copy landed intact: remote byte-size must equal local.
        local_size = os.path.getsize(zip_path)
        rc, out, _err = _run_ssh(["ssh"] + ssh_opts + [target, f"stat -c %s {remote_file}"], env)
        remote_size = out.strip()
        if rc != 0 or not remote_size.isdigit() or int(remote_size) != local_size:
            return (f"Gateway: FAILED (size mismatch: local={local_size} "
                    f"remote={remote_size or '?'})")

        # Prune to last KEEP_GATEWAY by mtime (newest kept).
        prune_cmd = (f"ls -1t {GATEWAY_REMOTE_DIR}/silvermere-tech-backup-*.zip 2>/dev/null "
                     f"| tail -n +{KEEP_GATEWAY + 1} | xargs -r rm -f")
        _run_ssh(["ssh"] + ssh_opts + [target, prune_cmd], env)

        size_mb = local_size / (1024 * 1024)
        return (f"Gateway: uploaded {fname} ({size_mb:.2f} MB) to {host}:{GATEWAY_REMOTE_DIR} "
                f"(size-verified, keep last {KEEP_GATEWAY})")
    except Exception as e:
        return f"Gateway: FAILED — {e}"
    finally:
        if askpass_path:
            try:
                os.unlink(askpass_path)
            except OSError:
                pass


def prune_imap(host, port, user, password, keep_n=KEEP_DAILY):
    """Delete oldest [BACKUP] emails in bertha's inbox, keeping the last keep_n."""
    try:
        with imaplib.IMAP4_SSL(host, port) as imap:
            imap.login(user, password)
            imap.select("INBOX")
            # Search for messages with BACKUP prefix
            status, data = imap.search(None, f'SUBJECT "{BACKUP_SUBJECT_PREFIX}"')
            if status != "OK":
                return
            uids = data[0].split()
            # uids are in ascending order (oldest first)
            to_delete = uids[:-keep_n] if len(uids) > keep_n else []
            for uid in to_delete:
                imap.store(uid, "+FLAGS", "\\Deleted")
            if to_delete:
                imap.expunge()
                print(f"IMAP prune: deleted {len(to_delete)} old backup(s), kept {min(len(uids), keep_n)}")
    except Exception as e:
        print(f"WARN: IMAP prune failed — {e} (backup still sent)", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description="Backup silvermere-tech org to email")
    parser.add_argument("--weekly", action="store_true",
                        help="Force weekly send (also send to Steven). Default: auto on Sundays.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Build zip and report size; do not send.")
    parser.add_argument("--no-ftp", action="store_true",
                        help="Skip Step 2 FTPS upload even if configured.")
    parser.add_argument("--no-gateway", action="store_true",
                        help="Skip Step 2b off-host gateway copy.")
    args = parser.parse_args()

    try:
        secrets = load_secrets()
    except FileNotFoundError:
        print(f"ERROR: secrets file not found: {SECRETS_FILE}", file=sys.stderr)
        sys.exit(1)

    smtp_host = secrets["HOSTINGER_SMTP_HOST"]
    smtp_port = int(secrets.get("HOSTINGER_SMTP_PORT", 465))
    imap_host = secrets.get("HOSTINGER_IMAP_HOST", "imap.hostinger.com")
    imap_port = int(secrets.get("HOSTINGER_IMAP_PORT", 993))
    sender = secrets["HOSTINGER_EMAIL"]
    password = secrets["HOSTINGER_EMAIL_APP_PASSWORD"]

    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M UTC")
    subject = f"{BACKUP_SUBJECT_PREFIX} silvermere-tech {date_str} {time_str}"

    is_weekly = args.weekly or (now.weekday() == 6)  # 6 = Sunday

    with tempfile.TemporaryDirectory() as tmp:
        zip_path = os.path.join(tmp, f"silvermere-tech-backup-{date_str}.zip")
        print(f"Building backup zip...")
        size_mb, skipped = build_zip(zip_path)
        print(f"Zip size: {size_mb:.2f} MB")

        if skipped:
            print(f"Excluded {len(skipped)} file(s) (credentials/binaries)")

        # Durable on-box retained copy FIRST — the must-have safety net, done
        # before email/FTP so a retained snapshot exists even if those steps fail.
        if args.dry_run:
            local_status = f"Local retain: dry-run — would copy to {LOCAL_RETAIN_DIR}"
        else:
            local_status = retain_local(zip_path, date_str)
        print(local_status)

        # Step 2 — FTPS off-site upload (runs first so email body can report status)
        if args.no_ftp:
            ftp_status = "FTP: skipped (--no-ftp)"
        elif args.dry_run:
            host_cfg = secrets.get("BACKUP_FTP_HOST", "").strip()
            ftp_status = (
                f"FTP: dry-run — would upload to {host_cfg}:{secrets.get('BACKUP_FTP_PATH', '/').strip() or '/'}"
                if host_cfg
                else "FTP: dry-run — not configured (BACKUP_FTP_HOST unset)"
            )
            ftp_prune_status = "FTP prune: dry-run — skipped"
        else:
            ftp_status = upload_to_ftp(secrets, zip_path)
            print(ftp_status)
            ftp_prune_status = prune_ftp(secrets)
            print(ftp_prune_status)

        # Step 2b — off-host copy to the OVH gateway (our own box, no spend).
        # The primary off-host path now that FTPS is unconfigured: guarantees a
        # copy survives total loss of this VM.
        if args.no_gateway:
            gw_status = "Gateway: skipped (--no-gateway)"
        elif args.dry_run:
            gw_host = secrets.get("TRAEFIK_GATEWAY_HOST", "").strip()
            gw_status = (f"Gateway: dry-run — would copy to {gw_host}:{GATEWAY_REMOTE_DIR}"
                         if gw_host else "Gateway: dry-run — not configured")
        else:
            gw_status = upload_to_gateway(secrets, zip_path)
            print(gw_status)

        over_limit = size_mb > SIZE_LIMIT_MB
        if over_limit:
            print(f"WARN: zip ({size_mb:.1f} MB) exceeds {SIZE_LIMIT_MB} MB limit — sending without attachment")
            body = (
                f"cortextOS org backup — {date_str}\n\n"
                f"Zip size: {size_mb:.1f} MB — EXCEEDS EMAIL LIMIT ({SIZE_LIMIT_MB} MB).\n"
                f"Attachment omitted. Retained copies:\n"
                f"  {local_status}\n"
                f"  {ftp_status}\n"
                f"  {gw_status}\n\n"
                f"Excluded {len(skipped)} credential/binary file(s).\n"
            )
            attach = None
        else:
            body = (
                f"cortextOS org backup — {date_str}\n\n"
                f"Zip size: {size_mb:.2f} MB\n"
                f"Contents: knowledge.md, context.json, goals.json, agent configs + bootstrap + memory, "
                f"docs, research, scripts, project docs (clearspeak-studio/app excluded).\n"
                f"Clean-backup: derived PDFs with a source .md are EXCLUDED (rebuild via "
                f"doc-to-pdf.js on restore); orphan/external PDFs are kept.\n"
                f"Excluded credentials: secrets.env, gsc-service-account.json, .env files.\n\n"
                f"Excluded {len(skipped)} additional credential/binary/derived file(s).\n\n"
                f"Retained copies:\n  {local_status}\n  {ftp_status}\n  {gw_status}\n\n"
                f"Restore: use scripts/restore.py to fetch + unzip from IMAP.\n"
            )
            attach = zip_path

        if args.dry_run:
            print(f"DRY RUN — would send to {DAILY_DEST}" + (f" + {WEEKLY_DEST}" if is_weekly else ""))
            print(f"DRY RUN — {ftp_status}")
            print(f"DRY RUN — {gw_status}")
            if over_limit:
                print("DRY RUN — zip over limit, would send without attachment")
            return

        # Daily send → bertha (self-archive)
        print(f"Sending daily backup to {DAILY_DEST}...")
        send_backup(smtp_host, smtp_port, sender, password, DAILY_DEST, subject, body, attach)
        print(f"OK  daily backup sent ({size_mb:.2f} MB {'+ attachment' if attach else 'no attachment'})")

        # IMAP prune — keep last KEEP_DAILY daily backups
        prune_imap(imap_host, imap_port, sender, password, keep_n=KEEP_DAILY)

        # Weekly send → Steven (offsite copy)
        if is_weekly:
            print(f"Sending weekly offsite copy to {WEEKLY_DEST}...")
            weekly_subject = f"{subject} [weekly]"
            send_backup(smtp_host, smtp_port, sender, password, WEEKLY_DEST,
                        weekly_subject, body, attach)
            print(f"OK  weekly backup sent to {WEEKLY_DEST}")


if __name__ == "__main__":
    main()
