#!/usr/bin/env bash
# org-projects nightly SNAPSHOT (task_1784286990142) — HISTORY for the swept
# projects (the FULL-zip sweep gives them a backup; this gives them diffs and
# recovery-from-bad-edit). Runs nightly after backup.py on the same cron.
#
# Design (chief-nodded 2026-07-17, threads 1784285619203/1784285691077):
# - External git-dir (~/.silvermere-projects-snapshot.git), worktree = org
#   root: invisible to every agent shell's `git status`, same isolation as
#   the prod-artifact repo.
# - Coverage DERIVED, never listed: the exclude file is REGENERATED each run
#   from the same criterion backup.py's sweep uses (a projects/ dir without
#   its own .git). A new project enters history the day it exists; a project
#   that grows its own repo leaves automatically. The swept/census counts are
#   printed every run — an empty derivation cannot read as coverage.
# - Per-file credential screen: the prod repo's pre-commit hook, verbatim
#   (path gate + content gates incl. apr1/bcrypt — adversarially tested
#   2026-07-09). A history that captures a credential is worse than no
#   history. HOOK REFUSAL POLICY: the hook refuses the WHOLE commit; this
#   script then reports the named offenders LOUDLY and exits nonzero — a
#   blocked snapshot is an incident line in the nightly cron read, never a
#   silent skip. (Two protections, different screens: a file blocked HERE may
#   still legitimately ride the screened zip; the divergence is per-file
#   legible in the output.)
set -uo pipefail
GD=/home/cortext/.silvermere-projects-snapshot.git
WT=/home/cortext/cortextos/orgs/silvermere-tech
G() { git --git-dir="$GD" --work-tree="$WT" "$@"; }

# --- 1. regenerate the exclude from the derived criterion ---
EX="$GD/info/exclude"
{
  echo "# GENERATED by projects-snapshot.sh $(date -u +%Y-%m-%dT%H:%M:%SZ) — DO NOT HAND-EDIT."
  echo "# Deny-by-default; un-ignores derived from the no-own-.git criterion."
  echo "/*"
  echo "!/projects/"
  echo "/projects/*"
} > "$EX"
census=0; swept=0
for p in "$WT"/projects/*/; do
  [ -d "$p" ] || continue
  census=$((census+1))
  name=$(basename "$p")
  if [ ! -e "$p/.git" ]; then
    swept=$((swept+1))
    echo "!/projects/$name/" >> "$EX"
  fi
done
# build/derived dirs never enter history
for d in node_modules .next dist build __pycache__ .cache .venv venv; do
  echo "$d/" >> "$EX"
done
# credential-bearing filename CLASS (mirrors the zip screen's names/suffixes)
cat >> "$EX" << 'CLASSEOF'
.env
*.env
.env.*
*.key
*.pem
CLASSEOF
# --- DISPOSITIONS: files the pre-commit screen refused, each read and ---
# --- dispositioned BY HAND with a dated reason. The hook stays VERBATIM ---
# --- (one predicate, shared with the prod repo — no drift); a NEW refusal ---
# --- is an incident line + a human read, never an automatic exclusion. ---
cat >> "$EX" << 'DISPEOF'
# 2026-07-17 engineer: apr1/bcrypt basicauth hashes (4) in a deploy snippet —
# the routes.yml class; hashes never enter history. (Rides the zip: the
# two-screens divergence, deliberate.)
/projects/image-curation-ui/deploy/traefik-snippet.yml
# 2026-07-17 engineer: security assessment PROSE quoting the bootstrap
# credential it assesses (line 24). Over-blocking history is the safe
# direction for credential-shaped prose; the doc rides the screened zip.
/projects/business-in-a-box/docs/odoo-dev-security-assessment-2026-06-08.md
# 2026-07-17 engineer: false-positive class — placeholder `api_key=YOUR_KEY`
# in research prose (line 282). Hook kept strict rather than taught
# placeholders; each future instance gets its own dated line here.
/projects/silvermere-platform/research/linkedin-jobs-rss-surface-2026-06-11.md
# 2026-07-17 engineer: EMBEDDED git repo inside a swept project (nested
# .git at repo-staging/). Its history is its own; snapshotting it would
# embed a gitlink. NOTE: nested repos are NOT bundle-discovered either
# (glob is projects/*/.git) — residual flagged to chief, not solved here.
/projects/discover-liwa/repo-staging/
DISPEOF
echo "projects snapshot: $swept of $census (census) covered by derived exclude"
[ "$swept" -gt 0 ] || { echo "ERROR: snapshot derivation swept ZERO projects — refusing (empty != covered)"; exit 2; }

# --- 2. stage + commit under the hook ---
# cd into the worktree: with an external git-dir, pathspecs resolve against
# the CWD — from anywhere else `add projects/` is a fatal no-match, and the
# staged-diff check below would read that FAILED producer as a clean zero
# (caught live on this script's first red run, 2026-07-17: the fatal printed
# one line above a "no changes" verdict).
cd "$WT" || { echo "ERROR: cannot cd to worktree $WT"; exit 2; }
if ! G add -A projects/; then
  echo "ERROR: snapshot tier FAILED — git add failed; nothing staged, nothing committed" >&2
  exit 1
fi
if G diff --cached --quiet; then
  echo "projects snapshot: no changes since last snapshot (clean zero — add exit-checked, staged diff empty)"
  exit 0
fi
n_staged=$(G diff --cached --name-only | wc -l)
if G commit -q -m "snapshot: $n_staged file(s) — $(date -u '+%Y-%m-%d %H:%MZ')"; then
  echo "projects snapshot: committed $n_staged file(s) -> $(G rev-parse --short HEAD)"
else
  echo "ERROR: snapshot tier FAILED — pre-commit screen refused (offending files named above); history NOT written this run" >&2
  G reset -q 2>/dev/null || true
  exit 1
fi
