import { Command } from 'commander';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { atomicWriteSync } from '../utils/atomic.js';

export const goalsCommand = new Command('goals')
  .description('Manage goals.json and auto-generate GOALS.md for agents');

const NAME_RE = /^[A-Za-z0-9_-]+$/;

function resolveAgentDir(agent: string, org: string): string {
  const frameworkRoot = process.env.CTX_FRAMEWORK_ROOT || process.cwd();
  return join(frameworkRoot, 'orgs', org, 'agents', agent);
}

/**
 * Render GOALS.md from goals.json. Shared by `generate-md` and `set` so the
 * two paths cannot drift. The rendered `Updated` line comes from goals.json's
 * own updated_at — rendering must NEVER stamp the clock, or regenerating
 * GOALS.md would silently refresh a stale stamp.
 */
function renderGoalsMd(agentDir: string, agent: string, org: string): void {
  const goalsJsonPath = join(agentDir, 'goals.json');
  const goalsMdPath = join(agentDir, 'GOALS.md');

  let data: Record<string, unknown>;
  try {
    data = JSON.parse(readFileSync(goalsJsonPath, 'utf-8'));
  } catch {
    process.stderr.write(`Failed to parse goals.json for ${agent}\n`);
    process.exit(1);
  }

  const goals = Array.isArray(data.goals) ? (data.goals as Array<string | { title: string }>) : [];
  const focus = typeof data.focus === 'string' ? data.focus : '';
  const bottleneck = typeof data.bottleneck === 'string' ? data.bottleneck : '';
  const updatedAt = typeof data.updated_at === 'string' ? data.updated_at : new Date().toISOString();
  const updatedBy = typeof data.updated_by === 'string' ? data.updated_by : '';

  const lines: string[] = [
    '# Goals',
    '',
    '> Auto-generated from goals.json. Do not edit this file directly.',
    `> To regenerate: \`cortextos goals generate-md --agent ${agent} --org ${org}\``,
    '',
    '## Focus',
    focus || '(not set — check with your orchestrator)',
    '',
    '## Goals',
  ];

  if (goals.length === 0) {
    lines.push('(none set — message your orchestrator to request today\'s goals)');
  } else {
    goals.forEach((g, i) => {
      const title = typeof g === 'string' ? g : (g as { title: string }).title;
      lines.push(`${i + 1}. ${title}`);
    });
  }

  lines.push(
    '',
    '## Bottleneck',
    bottleneck || '(none)',
    '',
    '## Updated',
    updatedBy ? `${updatedAt} (by ${updatedBy})` : updatedAt,
    '',
  );

  writeFileSync(goalsMdPath, lines.join('\n'), 'utf-8');
}

// cortextos goals generate-md --agent <name> --org <org>
goalsCommand
  .command('generate-md')
  .description('Regenerate GOALS.md from goals.json for an agent')
  .requiredOption('--agent <name>', 'Agent name')
  .requiredOption('--org <org>', 'Org name')
  .action((options: { agent: string; org: string }) => {
    if (!NAME_RE.test(options.agent) || !NAME_RE.test(options.org)) {
      process.stderr.write('Error: agent and org must be alphanumeric/dash/underscore only\n');
      process.exit(1);
    }

    const agentDir = resolveAgentDir(options.agent, options.org);
    const goalsJsonPath = join(agentDir, 'goals.json');

    if (!existsSync(goalsJsonPath)) {
      process.stderr.write(`goals.json not found at ${goalsJsonPath}\n`);
      process.exit(1);
    }

    renderGoalsMd(agentDir, options.agent, options.org);
    console.log(`Generated GOALS.md for ${options.agent}`);
  });

// cortextos goals set --agent <name> --org <org> [--focus F] [--goals JSON | --goal T ...]
//                     [--bottleneck B] --by <who>
//
// The framework writer of goals.json. updated_at is stamped from the clock at
// write time and cannot be supplied by the caller — there is no flag for it,
// deliberately: a hand-typed stamp is how a staleness check gets lied to.
goalsCommand
  .command('set')
  .description('Update goals.json fields and regenerate GOALS.md (updated_at is clock-stamped, never caller-supplied)')
  .requiredOption('--agent <name>', 'Agent name')
  .requiredOption('--org <org>', 'Org name')
  .requiredOption('--by <who>', 'Who is making this update (written to updated_by)')
  .option('--focus <text>', 'Focus line')
  .option('--goals <json>', 'Goals as a JSON array of strings, e.g. \'["goal one","goal two"]\'')
  .option('--goal <title>', 'A single goal (repeatable); alternative to --goals', (v: string, acc: string[]) => acc.concat(v), [] as string[])
  .option('--bottleneck <text>', 'Bottleneck line (pass "" to clear)')
  .action((options: {
    agent: string;
    org: string;
    by: string;
    focus?: string;
    goals?: string;
    goal: string[];
    bottleneck?: string;
  }) => {
    if (!NAME_RE.test(options.agent) || !NAME_RE.test(options.org)) {
      process.stderr.write('Error: agent and org must be alphanumeric/dash/underscore only\n');
      process.exit(1);
    }
    if (!NAME_RE.test(options.by)) {
      process.stderr.write('Error: --by must be alphanumeric/dash/underscore only\n');
      process.exit(1);
    }

    const hasFocus = options.focus !== undefined;
    const hasGoalsJson = options.goals !== undefined;
    const hasGoalFlags = options.goal.length > 0;
    const hasBottleneck = options.bottleneck !== undefined;

    if (!hasFocus && !hasGoalsJson && !hasGoalFlags && !hasBottleneck) {
      process.stderr.write('Error: nothing to set — pass at least one of --focus, --goals, --goal, --bottleneck\n');
      process.exit(1);
    }
    if (hasGoalsJson && hasGoalFlags) {
      process.stderr.write('Error: pass --goals OR repeated --goal, not both\n');
      process.exit(1);
    }

    let goals: string[] | undefined;
    if (hasGoalsJson) {
      let parsed: unknown;
      try {
        parsed = JSON.parse(options.goals as string);
      } catch {
        process.stderr.write('Error: --goals must be valid JSON\n');
        process.exit(1);
      }
      if (!Array.isArray(parsed) || !parsed.every((g) => typeof g === 'string')) {
        process.stderr.write('Error: --goals must be a JSON array of strings\n');
        process.exit(1);
      }
      goals = parsed as string[];
    } else if (hasGoalFlags) {
      goals = options.goal;
    }

    const agentDir = resolveAgentDir(options.agent, options.org);
    if (!existsSync(agentDir)) {
      process.stderr.write(`Agent directory not found at ${agentDir}\n`);
      process.exit(1);
    }

    const goalsJsonPath = join(agentDir, 'goals.json');
    let existing: Record<string, unknown> = {};
    if (existsSync(goalsJsonPath)) {
      try {
        existing = JSON.parse(readFileSync(goalsJsonPath, 'utf-8'));
      } catch {
        process.stderr.write(`Failed to parse existing goals.json for ${options.agent} — refusing to overwrite a file that may hold data\n`);
        process.exit(1);
      }
    }

    const next: Record<string, unknown> = { ...existing };
    if (hasFocus) next.focus = options.focus;
    if (goals !== undefined) next.goals = goals;
    if (hasBottleneck) next.bottleneck = options.bottleneck;
    // Stamped last, from the clock, unconditionally. No caller input reaches
    // these two fields.
    next.updated_at = new Date().toISOString();
    next.updated_by = options.by;

    atomicWriteSync(goalsJsonPath, JSON.stringify(next));
    renderGoalsMd(agentDir, options.agent, options.org);
    console.log(`Updated goals for ${options.agent} (updated_at ${next.updated_at} by ${options.by})`);
  });
